/*
 * This file was automatically generated by EvoSuite
 * Sun Oct 20 10:19:08 GMT 2024
 */

package ex07;

import org.junit.Test;
import static org.junit.Assert.*;
import ex07.Calculator;


public class Calculator_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      int int0 = calculator0.run(1165, 1165, "/");
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      int int0 = calculator0.run(0, (-362), "*");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      int int0 = calculator0.run(0, 1394, "-");
      assertEquals((-1394), int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      int int0 = calculator0.run((-1994619633), (-1994638843), "+");
      assertEquals(305708820, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      int int0 = calculator0.run(1, (-1), "/");
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      // Undeclared exception!
      try { 
        calculator0.run(0, (-1597), (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      int int0 = calculator0.run(1, 0, "/");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      int int0 = calculator0.run((-2013655293), 267656710, ",");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      int int0 = calculator0.run((-24), (-24), "-");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      int int0 = calculator0.run((-143528992), (-143528992), "*");
      assertEquals(1427440640, int0);
  }
}
