/*
 * This file was automatically generated by EvoSuite
 * Sun Oct 20 10:21:02 GMT 2024
 */

package ex07;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ex07.Executer;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;


public class Executer_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Executer executer0 = new Executer();
      // Undeclared exception!
      try { 
        executer0.run((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ex07.Formula", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Executer executer0 = new Executer();
      int int0 = executer0.run("");
      assertEquals(0, int0);
  }
}
